// Code generated by "stringer -output=constants_string.go -type=tagType --trimprefix=tag"; DO NOT EDIT.

package pushreceiver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tagHeartbeatPing-0]
	_ = x[tagHeartbeatAck-1]
	_ = x[tagLoginRequest-2]
	_ = x[tagLoginResponse-3]
	_ = x[tagClose-4]
	_ = x[tagMessageStanza-5]
	_ = x[tagPresenceStanza-6]
	_ = x[tagIqStanza-7]
	_ = x[tagDataMessageStanza-8]
	_ = x[tagBatchPresenceStanza-9]
	_ = x[tagStreamErrorStanza-10]
	_ = x[tagHTTPRequest-11]
	_ = x[tagHTTPResponse-12]
	_ = x[tagBindAccountRequest-13]
	_ = x[tagBindAccountResponse-14]
	_ = x[tagTalkMetadata-15]
	_ = x[tagNumProtoTypes-16]
}

const _tagType_name = "HeartbeatPingHeartbeatAckLoginRequestLoginResponseCloseMessageStanzaPresenceStanzaIqStanzaDataMessageStanzaBatchPresenceStanzaStreamErrorStanzaHTTPRequestHTTPResponseBindAccountRequestBindAccountResponseTalkMetadataNumProtoTypes"

var _tagType_index = [...]uint8{0, 13, 25, 37, 50, 55, 68, 82, 90, 107, 126, 143, 154, 166, 184, 203, 215, 228}

func (i tagType) String() string {
	if i >= tagType(len(_tagType_index)-1) {
		return "tagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tagType_name[_tagType_index[i]:_tagType_index[i+1]]
}
