[settings]
minimum_release_age = "7d"

[tools]
gitleaks = "latest"
go = "latest"
golangci-lint = "latest"
lefthook = "latest"
node = "26"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
protoc = "latest"
